dependencies:
    - OpenZeppelin/openzeppelin-contracts@4.8.2
compiler:
    solc:
        remappings:
            - '@openzeppelin-contracts=OpenZeppelin/openzeppelin-contracts@4.8.2'
dotenv: .env
wallets:
    from_key_testnet: ${PRIVATE_KEY_TESTNET}
    from_key_mainnet: ${PRIVATE_KEY_MAINNET}
